version: '3.8'
services:

  php:
    build:
      context: .
      target: php_app
    restart: unless-stopped
    volumes:
      - ./app:/var/www/app
  
  nginx:
    build:
      context: .
      target: nginx_app
    volumes:
      - ./app:/var/www/app
      # - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - php

