version: '3.8'
services:

  php:
    build:
      context: .
      target: php_app
    restart: unless-stopped
    volumes:
      - ./app:/var/www/app
      - app_vendor:/var/www/app/vendor
  
  nginx:
    build:
      context: .
      target: nginx_app
    volumes:
      - ./app:/var/www/app
      - app_vendor:/var/www/app/vendor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - php

volumes:
  app_vendor:

